nelmio_cors:
  defaults:
    allow_origin: ['*'] #This is just for to make it easier to test. Should have a specific origin if production or real development.
    allow_headers: ['Content-Type', 'Authorization']
    allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
    max_age: 3600
  paths:
    '^/api/': ~